In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
day_inp = '20'
mon_inp = 'Apr'

In [3]:
df = pd.read_csv('ODH Model pincode Tracker.csv')
dff1 = pd.read_excel("GTNL Report -"+day_inp+"th "+mon_inp+"'25.xlsx", sheet_name='Base Data for Work')

In [4]:
df1 = df[['ODH/MDH Name','Type','Vendor','Zone','State']]
df1

                     ODH/MDH Name        Type      Vendor   Zone        State
0             SASThuravoorODH_THO         ODH         SAS  SOUTH       KERALA
1               RJSCImphalODH_IMP         ODH        RJSC   EAST      MANIPUR
2              ImphalSplitMDH_IMP  MDH in Bin        RJSC   EAST      MANIPUR
3     ElasticRunBhawanipurODH_KOL         ODH  ELASTICRUN   EAST  WEST BENGAL
4             CABTGariahatODH_KOL         ODH   LOADSHARE   EAST  WEST BENGAL
...                           ...         ...         ...    ...          ...
2404                   UCCMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2405                JhaldaHub_JAA         ODH   LOADSHARE   EAST  WEST BENGAL
2406              GangadraMDH_KDO         MDH   SHADOWFAX   WEST      GUJARAT
2407             MawsynramMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2408                MawpatMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA

[2409 rows x 5 columns]

In [5]:
df2 = df1.drop_duplicates()
df2

                     ODH/MDH Name        Type      Vendor   Zone        State
0             SASThuravoorODH_THO         ODH         SAS  SOUTH       KERALA
1               RJSCImphalODH_IMP         ODH        RJSC   EAST      MANIPUR
2              ImphalSplitMDH_IMP  MDH in Bin        RJSC   EAST      MANIPUR
3     ElasticRunBhawanipurODH_KOL         ODH  ELASTICRUN   EAST  WEST BENGAL
4             CABTGariahatODH_KOL         ODH   LOADSHARE   EAST  WEST BENGAL
...                           ...         ...         ...    ...          ...
2404                   UCCMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2405                JhaldaHub_JAA         ODH   LOADSHARE   EAST  WEST BENGAL
2406              GangadraMDH_KDO         MDH   SHADOWFAX   WEST      GUJARAT
2407             MawsynramMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2408                MawpatMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA

[2409 rows x 5 columns]

In [6]:
df2.rename(columns={'Vendor':'Vendor Name','ODH/MDH Name':'HubName'},inplace=True)
df2['HubName']= df2['HubName'].str.upper()
df2['Zone']=df2['Zone'].str.strip()
df2

                          HubName        Type Vendor Name   Zone        State
0             SASTHURAVOORODH_THO         ODH         SAS  SOUTH       KERALA
1               RJSCIMPHALODH_IMP         ODH        RJSC   EAST      MANIPUR
2              IMPHALSPLITMDH_IMP  MDH in Bin        RJSC   EAST      MANIPUR
3     ELASTICRUNBHAWANIPURODH_KOL         ODH  ELASTICRUN   EAST  WEST BENGAL
4             CABTGARIAHATODH_KOL         ODH   LOADSHARE   EAST  WEST BENGAL
...                           ...         ...         ...    ...          ...
2404                   UCCMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2405                JHALDAHUB_JAA         ODH   LOADSHARE   EAST  WEST BENGAL
2406              GANGADRAMDH_KDO         MDH   SHADOWFAX   WEST      GUJARAT
2407             MAWSYNRAMMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA
2408                MAWPATMDH_SHL         MDH  LIGHTWINGS   EAST    MEGHALAYA

[2409 rows x 5 columns]

In [7]:
dff1.rename(columns={'CurrentHub':'HubName'},inplace=True)
dff1['HubName']= dff1['HubName'].str.upper()
dff1

,Shipment Type,return_create_date,source_facility_id,shipment_id,tracking_id,return_amount,return_reason,product_id,PRTO Reason,fulfill_item_unit_id,...,Amount recovery status(Lost),LatestUpdateTime,LastReceiveTime,FLO Status,Sub Attributes.1,Error type.1,Ticket/Deposit no.1,Amount recovery status(Lost).1,LatestUpdateTime.1,New Addition
0,BRSNR,2025-03-18 00:00:00,guw_pal_wh_g_01,S9648729177,FMPC4621554455,339,ORC_validated with customer,NaN,NaN,12.0,...,NaN,NaN,2025-03-24 12:48:00,Undelivered_Attempted,NaN,NaN,NaN,NaN,NaN,NaN
1,BRSNR,2025-03-22 00:00:00,ben_ane_wh_g_01,S13565212375,FMPP2934052432,153,Damaged_shipment,NaN,NaN,1.0,...,NaN,NaN,2025-04-17 20:50:00,rto_confirmed,NaN,NaN,NaN,NaN,NaN,NaN
2,RTO,2025-03-18 00:00:00,pat_dho_wh_g_01,S13487075005,FMPC4607358135,341,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,2025-03-09 13:44:00,rto_confirmed,NaN,NaN,NaN,NaN,NaN,NaN
3,RTO,2025-03-22 00:00:00,del_tau_wh_g_01,S9667715447,FMPP2936095291,740,ORC_validated with customer,NaN,NaN,6.0,...,NaN,NaN,2025-03-27 14:58:00,Undelivered_Attempted,NaN,NaN,NaN,NaN,NaN,NaN
4,RTO,2025-03-02 00:00:00,ahm_bav_wh_g_01,S7837606164,FMPC4574322670,3547,WHATSAPP,NaN,NaN,20.0,...,NaN,NaN,2025-03-01 11:04:00,Undelivered_Attempted,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50217,PRTO,2025-03-01 06:59:00,coi_app_wh_g_01,333744450106281209000,FMPC4573704378,317,NaN,DEOFCFYEY69WGSYD,MISSING_ITEM,NaN,...,NaN,NaN,2025-03-04 05:31:00,partially_delivered,NaN,NaN,NaN,NaN,NaN,NaN
50218,PRTO,2025-03-01 06:50:00,bhu_pit_wh_g_01,333743648098288208000,FMPP2890576118,853,NaN,EDOEY7YEPFS2GYUH,MISSING_ITEM,NaN,...,NaN,NaN,2025-03-04 03:57:00,partially_delivered,NaN,NaN,NaN,NaN,NaN,NaN
50219,PRTO,2025-03-01 06:47:00,luc_has_wh_g_01,433734228218212205000,FMPC4568708681,557,NaN,LDTFG5JFMPRZJFXQ,MISSING_ITEM,NaN,...,NaN,NaN,2025-02-28 12:57:00,partially_delivered,NaN,NaN,NaN,NaN,NaN,NaN
50220,PRTO,2025-03-01 06:44:00,nag_hin_3pl_g_01,333740573568730202002,FMPC4570961638,36,NaN,CHPEU6ZH7AYY6KHC,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,2025-02-28 20:18:00,partially_delivered,NaN,NaN,NaN,NaN,NaN,NaN
50221,PRTO,2025-03-01 02:55:00,pun_cha_3pl_g_01,333744796574704200001,FMPP2891109910,24,NaN,SOUFHSFDXHS5EFEX,PRODUCT_DAMAGE,NaN,...,NaN,NaN,2025-03-01 02:30:00,partially_delivered,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df3 = pd.merge(dff1, df2, on = "HubName", how = "left")
df3

,Shipment Type,return_create_date,source_facility_id,shipment_id,tracking_id,return_amount,return_reason,product_id,PRTO Reason,fulfill_item_unit_id,...,Sub Attributes.1,Error type.1,Ticket/Deposit no.1,Amount recovery status(Lost).1,LatestUpdateTime.1,New Addition,Type,Vendor Name,Zone_y,State
0,BRSNR,2025-03-18 00:00:00,guw_pal_wh_g_01,S9648729177,FMPC4621554455,339,ORC_validated with customer,NaN,NaN,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BRSNR,2025-03-22 00:00:00,ben_ane_wh_g_01,S13565212375,FMPP2934052432,153,Damaged_shipment,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RTO,2025-03-18 00:00:00,pat_dho_wh_g_01,S13487075005,FMPC4607358135,341,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RTO,2025-03-22 00:00:00,del_tau_wh_g_01,S9667715447,FMPP2936095291,740,ORC_validated with customer,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RTO,2025-03-02 00:00:00,ahm_bav_wh_g_01,S7837606164,FMPC4574322670,3547,WHATSAPP,NaN,NaN,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50217,PRTO,2025-03-01 06:59:00,coi_app_wh_g_01,333744450106281209000,FMPC4573704378,317,NaN,DEOFCFYEY69WGSYD,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50218,PRTO,2025-03-01 06:50:00,bhu_pit_wh_g_01,333743648098288208000,FMPP2890576118,853,NaN,EDOEY7YEPFS2GYUH,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50219,PRTO,2025-03-01 06:47:00,luc_has_wh_g_01,433734228218212205000,FMPC4568708681,557,NaN,LDTFG5JFMPRZJFXQ,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50220,PRTO,2025-03-01 06:44:00,nag_hin_3pl_g_01,333740573568730202002,FMPC4570961638,36,NaN,CHPEU6ZH7AYY6KHC,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50221,PRTO,2025-03-01 02:55:00,pun_cha_3pl_g_01,333744796574704200001,FMPP2891109910,24,NaN,SOUFHSFDXHS5EFEX,PRODUCT_DAMAGE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df4 = df3.dropna(subset = 'Vendor Name', how = 'all')
df4

,Shipment Type,return_create_date,source_facility_id,shipment_id,tracking_id,return_amount,return_reason,product_id,PRTO Reason,fulfill_item_unit_id,...,Sub Attributes.1,Error type.1,Ticket/Deposit no.1,Amount recovery status(Lost).1,LatestUpdateTime.1,New Addition,Type,Vendor Name,Zone_y,State
18,RTO,2025-03-22 00:00:00,guw_pal_wh_g_01,S9636989027,FMPC4610193929,1037,ORC_validated with customer,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,RJSC,EAST,MANIPUR
43,RTO,2025-03-22 00:00:00,ahm_bav_wh_g_01,S7902802944,FMPC4626194596,817,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,PRINCY,WEST,GUJARAT
64,RTO,2025-03-22 00:00:00,del_tau_wh_g_01,S9660948537,FMPP2931495634,635,order_cancelled,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,HARYANA
98,RTO,2025-03-18 00:00:00,hyd_pud_wh_g_01,S12465778076,FMPP2919145517,2687,order_cancelled,NaN,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,DEPENDO,SOUTH,TELANGANA
131,RTO,2025-03-02 00:00:00,jai_san_wh_g_01,S7831880174,FMPP2889260058,338,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50119,PRTO,2025-03-01 09:48:00,jai_san_wh_g_01,433751378929536200000,FMPC4575097332,1072,NaN,GHEEU5KDFHN9PCKH,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN
50177,PRTO,2025-03-01 08:38:00,ahm_bav_wh_g_01,433735241403981202000,FMPC4575639038,249,NaN,FLRF9D4GNH62TVEH,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,ELASTICRUN,WEST,GUJARAT
50180,PRTO,2025-03-01 08:34:00,ahm_bav_wh_g_01,333736158025524202000,FMPC4575686259,36,NaN,CHPFG2BQVPYH2PHR,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MDH in Bin,SHIPLOCAL,WEST,GUJARAT
50183,PRTO,2025-03-01 08:27:00,hyd_pud_wh_g_01,333732431898021205000,FMPP2891554368,20,NaN,CKBF6TF7ZGBSPY5K,MISSING_ITEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,BABA,SOUTH,TELANGANA
50197,PRTO,2025-03-01 08:06:00,mal_mou_3pl_g_01,433739761583363200000,FMPP2889115876,52,NaN,CAFETEGHFD5Y4NBK,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MDH,SMARTPRO,EAST,WEST BENGAL

In [10]:
df5 = df4[df4["PRTO Reason"]!="MISSING_ITEM"]
df5

,Shipment Type,return_create_date,source_facility_id,shipment_id,tracking_id,return_amount,return_reason,product_id,PRTO Reason,fulfill_item_unit_id,...,Sub Attributes.1,Error type.1,Ticket/Deposit no.1,Amount recovery status(Lost).1,LatestUpdateTime.1,New Addition,Type,Vendor Name,Zone_y,State
18,RTO,2025-03-22 00:00:00,guw_pal_wh_g_01,S9636989027,FMPC4610193929,1037,ORC_validated with customer,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,RJSC,EAST,MANIPUR
43,RTO,2025-03-22 00:00:00,ahm_bav_wh_g_01,S7902802944,FMPC4626194596,817,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,PRINCY,WEST,GUJARAT
64,RTO,2025-03-22 00:00:00,del_tau_wh_g_01,S9660948537,FMPP2931495634,635,order_cancelled,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,HARYANA
98,RTO,2025-03-18 00:00:00,hyd_pud_wh_g_01,S12465778076,FMPP2919145517,2687,order_cancelled,NaN,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,DEPENDO,SOUTH,TELANGANA
131,RTO,2025-03-02 00:00:00,jai_san_wh_g_01,S7831880174,FMPP2889260058,338,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50063,PRTO,2025-03-01 14:56:00,hyd_pud_wh_g_01,333732926425871209000,FMPP2891522552,28,NaN,GNMGHBRPVHFGFTQJ,PRODUCT_DAMAGE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,DEPENDO,SOUTH,TELANGANA
50095,PRTO,2025-03-01 10:44:00,luc_has_wh_g_01,333749631983294200000,FMPC4572807822,403,NaN,EDOFCSBGS8AYG6HK,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MDH in Bin,CONNECTINDIA,NORTH,UTTAR PRADESH
50101,PRTO,2025-03-01 10:34:00,pat_dho_wh_g_01,333732195031743200004,FMPP2891572474,31,NaN,CKBEUHBPT99SD2VA,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MDH in Bin,PATLIPUTRA,EAST,BIHAR
50119,PRTO,2025-03-01 09:48:00,jai_san_wh_g_01,433751378929536200000,FMPC4575097332,1072,NaN,GHEEU5KDFHN9PCKH,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN
50197,PRTO,2025-03-01 08:06:00,mal_mou_3pl_g_01,433739761583363200000,FMPP2889115876,52,NaN,CAFETEGHFD5Y4NBK,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MDH,SMARTPRO,EAST,WEST BENGAL

In [11]:
def assign_bucket(return_amount):
    return ">=2k" if  return_amount >= 2000 else "<2k"

In [12]:
df5["Bucket"] = df5["return_amount"].apply(assign_bucket)
df5

C:\Users\prajwal.d1\AppData\Local\Temp\ipykernel_6204\2372091861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["Bucket"] = df5["return_amount"].apply(assign_bucket)

,Shipment Type,return_create_date,source_facility_id,shipment_id,tracking_id,return_amount,return_reason,product_id,PRTO Reason,fulfill_item_unit_id,...,Error type.1,Ticket/Deposit no.1,Amount recovery status(Lost).1,LatestUpdateTime.1,New Addition,Type,Vendor Name,Zone_y,State,Bucket
18,RTO,2025-03-22 00:00:00,guw_pal_wh_g_01,S9636989027,FMPC4610193929,1037,ORC_validated with customer,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,ODH,RJSC,EAST,MANIPUR,<2k
43,RTO,2025-03-22 00:00:00,ahm_bav_wh_g_01,S7902802944,FMPC4626194596,817,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,ODH,PRINCY,WEST,GUJARAT,<2k
64,RTO,2025-03-22 00:00:00,del_tau_wh_g_01,S9660948537,FMPP2931495634,635,order_cancelled,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,HARYANA,<2k
98,RTO,2025-03-18 00:00:00,hyd_pud_wh_g_01,S12465778076,FMPP2919145517,2687,order_cancelled,NaN,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,ODH,DEPENDO,SOUTH,TELANGANA,>=2k
131,RTO,2025-03-02 00:00:00,jai_san_wh_g_01,S7831880174,FMPP2889260058,338,order_cancelled,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN,<2k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50063,PRTO,2025-03-01 14:56:00,hyd_pud_wh_g_01,333732926425871209000,FMPP2891522552,28,NaN,GNMGHBRPVHFGFTQJ,PRODUCT_DAMAGE,NaN,...,NaN,NaN,NaN,NaN,NaN,ODH,DEPENDO,SOUTH,TELANGANA,<2k
50095,PRTO,2025-03-01 10:44:00,luc_has_wh_g_01,333749631983294200000,FMPC4572807822,403,NaN,EDOFCSBGS8AYG6HK,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,MDH in Bin,CONNECTINDIA,NORTH,UTTAR PRADESH,<2k
50101,PRTO,2025-03-01 10:34:00,pat_dho_wh_g_01,333732195031743200004,FMPP2891572474,31,NaN,CKBEUHBPT99SD2VA,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,MDH in Bin,PATLIPUTRA,EAST,BIHAR,<2k
50119,PRTO,2025-03-01 09:48:00,jai_san_wh_g_01,433751378929536200000,FMPC4575097332,1072,NaN,GHEEU5KDFHN9PCKH,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,ODH,IDENTIFYPLUS,NORTH,RAJASTHAN,<2k
50197,PRTO,2025-03-01 08:06:00,mal_mou_3pl_g_01,433739761583363200000,FMPP2889115876,52,NaN,CAFETEGHFD5Y4NBK,PRODUCT_NOT_REQUIRED,NaN,...,NaN,NaN,NaN,NaN,NaN,MDH,SMARTPRO,EAST,WEST BENGAL,<2k

In [13]:
df5.to_excel("gtnl_pendency"+day_inp+mon_inp+".xlsx")